# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  jetcookies:
    image: jetcookies
    build:
      context: .
      dockerfile: JETCookies/Dockerfile
    ports:
      - 5000:5000
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "1Secure*Password1"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
  vueui:
    image: vueui
    build:
      context: vue-client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8080