version: '3.4'

services:
  jetcookies:
    image: ${DOCKER_REGISTRY-}jetcookies
    build:
      context: .
      dockerfile: JETCookies/Dockerfile
    ports:
        - "8080:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "1Secure*Password1"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"