// <auto-generated />
using JETCookies.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JETCookies.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210611200645_ManyToManyTable")]
    partial class ManyToManyTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JETCookies.Models.Cookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CookieItems");
                });

            modelBuilder.Entity("JETCookies.Models.CookieIngredient", b =>
                {
                    b.Property<int>("CookieId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("CookieId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CookieIngredients");
                });

            modelBuilder.Entity("JETCookies.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngredientItems");
                });

            modelBuilder.Entity("JETCookies.Models.CookieIngredient", b =>
                {
                    b.HasOne("JETCookies.Models.Cookie", "Coookie")
                        .WithMany("CookieIngredients")
                        .HasForeignKey("CookieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JETCookies.Models.Ingredient", "Ingredient")
                        .WithMany("CookieIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coookie");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("JETCookies.Models.Cookie", b =>
                {
                    b.Navigation("CookieIngredients");
                });

            modelBuilder.Entity("JETCookies.Models.Ingredient", b =>
                {
                    b.Navigation("CookieIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
